### ISSUE TITLE
!play <songname/url> command gives error

### ISSUE THREAD

**Issue by hirshi001** [TechnoVisionDev/TechnoBot#14]
Whenever the !play command is used, a message saying "An error occurred!" is send to the channel.
How to replicate
Have the bot join voice channel
!play (Whatever Song)
Example
!play Loop de Loop

**Comment by xf8b** [comment]
~~valve~~ pls fix

**Comment by Sparky200** [comment]
Please give the error printed to console. We can't fix something if we don't have the stack trace or exception.

**Comment by xf8b** [comment]
cant really give the thing logged to the log

**Comment by Sparky200** [comment]
There's nothing we can do without logs. Is there a reason the OP cannot access console?

**Comment by hirshi001** [comment]
How are we supposed to get the logs? The only message which the bot sends to the channel is
"An error occurred!"

**Comment by Sparky200** [comment]
Yeah, the bot doesn't post the exception to regular users. Are you not hosting the bot?

**Comment by hirshi001** [comment]
No, its on technovision's server.

**Comment by xf8b** [comment]
bruh

**Comment by Sparky200** [comment]
That's... completely different. You should report that on the server, nothing can be fixed without logs.
Issues on this repo are meant for issues and improvements to the original source code, not individual instances of the bot.
If you find an issue while running the bot for yourself, you post your problem here, or else report it to the bot host. The bot host should come here for issues, or they can fork and attempt to fix it on their own.
